---
apiVersion: storage.gcp.crossplane.io/v1alpha3
kind: Bucket
metadata:
  name: ${{values.system}}-${{values.env}}-bucket
  namespace: ${{values.system}}
  labels:
    backstage.io/kubernetes-id: ${{values.system}}
  annotations:
    # Note that this will be the actual bucket name so it has to be globally unique/available.
    crossplane.io/external-name: ${{values.system}}-${{values.env}}-bucket
spec:
  location: US
  storageClass: MULTI_REGIONAL
  providerConfigRef:
    name: gcp-provider
  deletionPolicy: Delete